services:
  - type: web
    name: attendance-api
    env: python
    region: ohio
    buildCommand: "bash ./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: DEBUG
        value: "False"
